server:
  port: 9062

# Database properties
spring:
  cloud:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    platform: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:veera}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_SERVER_PORT:5432}/${DB_NAME:mbk_database}?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: false
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: mbk_music
        # Set the ddl-auto to none before pushing to production.
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
# Information that gets displayed in the spring admin UI
# ------------------------------------------------------
info:
  app:
    name: mbkmusic-mbkmusic-service
    description: Music app on Dr. MBK of his compositions